#!/usr/bin/env node
// scripts/deploy-check.mjs — is every edge function in the repo actually DEPLOYED? (#472)
//
//   pnpm deploy:check
//
// READ-ONLY, and that is the whole design constraint. It never deploys, never links, never
// writes. In particular it never goes near `supabase/.temp/linked-project.json`: that file is a
// single global which `supabase db push` and `supabase functions deploy` both obey, so a script
// that retargeted the link to look at production could leave the next push aimed there. Both
// project refs are constants here and every request names one explicitly — "whatever is linked"
// is never an input.
//
// WHY THIS EXISTS. Three guards look like they cover this and none of them can see a deploy:
//   * `supabase/functions/_shared/config-invariants.test.ts` asserts the auth-posture table in
//     `supabase/config.toml`. It reads a FILE, so it is equally green whether the function is
//     deployed to zero projects or two.
//   * `#80` is the production ledger and it counts MIGRATIONS. #468's `moderation-enforce`
//     migration was applied on production; only the function was missing, so #80 was
//     structurally incapable of showing it.
//   * `docs/RELEASE-RUNBOOK.md` makes deploy claims in PROSE — a sentence, not a check. R-8 §4
//     now calls this script instead of asserting from memory.
// #468 (production behind staging) sat unnoticed for a week; the same walk found staging's
// `stripe-webhook` ten days stale and silently failing to issue paid tickets. Both directions,
// hence a symmetric report.
//
// WHAT IT GATES, AND WHAT IT ONLY REPORTS. Exit is non-zero for exactly one thing: a repo
// function that is missing from staging or production (#472 acceptance 2). Everything else —
// deploy age, an orphan slug deployed with no repo directory, a `verify_jwt` that disagrees
// with `config.toml`, a Vault-name difference — is PRINTED for a human to judge. Staleness has
// no honest threshold: `announce-cycle` legitimately has not changed in months, while ten days
// was fatal for `stripe-webhook`. A number a human reads beats a gate that cries wolf.
//
// SECRETS. The Management API token is the operator's own CLI credential, resolved at run time
// from $SUPABASE_ACCESS_TOKEN or the macOS keychain — same helper shape as
// `scripts/staging-refresh.mjs`. It is never printed and never written anywhere. The Vault
// comparison reads `select name from vault.secrets`: NAMES ONLY, never `decrypted_secret`.
//
// NO DEPENDENCIES, ON PURPOSE — same reasoning as staging-refresh.mjs / upload-staging-media.mjs:
// a repo-root script cannot import from the workspace under node-linker=hoisted, and two fetches
// need no library.
//
// The pure half (everything above `main()`) is exported and unit-tested from
// `packages/api/src/deploy-check.test.ts`, the way `scripts/check-i18n-hardcoded.mjs` is tested
// from `packages/i18n`. That is what keeps STAGING_ONLY_SECRETS a tested invariant rather than a
// line someone later "simplifies".

import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const STAGING_REF = 'eralyiwkfrpqsawivegz';
export const PRODUCTION_REF = 'kwzeiqvrnnaagccyoose';

/**
 * Vault secret names that are EXPECTED on staging and must NEVER exist on production.
 *
 * `app.settings.environment` is one of the two factors guarding
 * `supabase/staging-seed/seed-staging.sql` (the other is the operator typing
 * `set app.settings.seed_confirm = 'yes'`). Its absence on production is CORRECT. A naive diff
 * would report it as drift and invite someone to "fix" it — and fixing it would arm the staging
 * seed against the production database. So it is declared here, printed as expected, and
 * asserted in the test: this list is the reason, not a filter.
 */
export const STAGING_ONLY_SECRETS = ['app.settings.environment'];

/** Deployable functions in the repo: a `supabase/functions/<slug>/index.ts`, minus `_shared`. */
export function readRepoFunctions(functionsDir) {
  return readdirSync(functionsDir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && e.name !== '_shared')
    .map((e) => e.name)
    .filter((name) => existsSync(join(functionsDir, name, 'index.ts')))
    .sort();
}

/**
 * The declared auth posture per function, read off `supabase/config.toml`.
 * Deliberately a small regex rather than a TOML parser: this file is generated by the CLI in one
 * shape (`[functions.<slug>]` then `verify_jwt = <bool>`), and a dependency-free script beats a
 * complete one here. A key it cannot read is simply absent from the map, never guessed.
 */
export function parseConfigPostures(toml) {
  const postures = new Map();
  let current = null;
  for (const line of toml.split('\n')) {
    const section = /^\[functions\.([A-Za-z0-9_-]+)\]\s*$/.exec(line);
    if (section) {
      current = section[1];
      continue;
    }
    if (line.startsWith('[')) {
      current = null;
      continue;
    }
    const jwt = /^\s*verify_jwt\s*=\s*(true|false)\s*$/.exec(line);
    if (jwt && current) postures.set(current, jwt[1] === 'true');
  }
  return postures;
}

/**
 * The symmetric set comparison. `missing*` is the only thing that gates (#472 acceptance 2);
 * `orphan*` is the other direction — a slug deployed with no repo directory, which a rename or a
 * deletion leaves behind — and is reported, not gated, because deleting a live function is a
 * decision, not a fix a script should imply.
 */
export function diffDeployments({ repo, staging, production }) {
  const missing = (deployed) => repo.filter((slug) => !deployed.includes(slug));
  const orphans = (deployed) => deployed.filter((slug) => !repo.includes(slug)).sort();
  return {
    missingFromStaging: missing(staging),
    missingFromProduction: missing(production),
    orphanStaging: orphans(staging),
    orphanProduction: orphans(production),
  };
}

/**
 * Vault NAMES only. `expectedStagingOnly` is split out of `stagingOnly` so the report can say
 * "this one is correct" instead of listing it as drift — see STAGING_ONLY_SECRETS.
 */
export function diffSecrets({ staging, production, stagingOnlyByDesign = STAGING_ONLY_SECRETS }) {
  const only = (a, b) => a.filter((name) => !b.includes(name)).sort();
  const stagingOnly = only(staging, production);
  return {
    stagingOnly: stagingOnly.filter((name) => !stagingOnlyByDesign.includes(name)),
    expectedStagingOnly: stagingOnly.filter((name) => stagingOnlyByDesign.includes(name)),
    productionOnly: only(production, staging),
    // A staging-only-by-design secret that turned up on PRODUCTION is the dangerous direction,
    // and it is the one a plain diff would never call out.
    unexpectedOnProduction: stagingOnlyByDesign.filter((name) => production.includes(name)),
  };
}

/**
 * A deployed `verify_jwt` that disagrees with `config.toml`. Rule 8's posture table is asserted
 * against the file; nothing asserts it against what is actually running, which is the same class
 * of gap as an undeployed function. Reported, not gated.
 */
export function postureDrift({ postures, deployed }) {
  return deployed
    .filter((fn) => postures.has(fn.slug) && postures.get(fn.slug) !== fn.verify_jwt)
    .map((fn) => ({ slug: fn.slug, declared: postures.get(fn.slug), deployed: fn.verify_jwt }))
    .sort((a, b) => a.slug.localeCompare(b.slug));
}

/** Human age of a deploy. Clock injected — a function that reads it internally cannot be tested. */
export function formatAge(updatedAtMs, nowMs) {
  if (typeof updatedAtMs !== 'number' || !Number.isFinite(updatedAtMs)) return '?';
  const minutes = Math.floor((nowMs - updatedAtMs) / 60_000);
  if (minutes < 0) return 'just now';
  if (minutes < 60) return `${minutes}m`;
  const hours = Math.floor(minutes / 60);
  if (hours < 48) return `${hours}h`;
  return `${Math.floor(hours / 24)}d`;
}

// ─── everything below reaches the network ────────────────────────────────────────────────────

const die = (msg) => {
  console.error(`\n✗ ${msg}\n`);
  process.exit(1);
};

/** The operator's own Management API credential. Never printed, never persisted. */
function accessToken() {
  const env = process.env.SUPABASE_ACCESS_TOKEN;
  if (env) return env.trim();
  if (process.platform === 'darwin') {
    try {
      return execFileSync(
        'security',
        ['find-generic-password', '-s', 'Supabase CLI', '-a', 'supabase', '-w'],
        { encoding: 'utf8' },
      ).trim();
    } catch {
      /* fall through to the hint */
    }
  }
  die(`no Management API token. Either:

  export SUPABASE_ACCESS_TOKEN=sbp_…       # from app.supabase.com/account/tokens
  supabase login                            # stores one in the macOS keychain

This is the operator's own account credential, not a project secret.`);
}

async function api(path, token, init = {}) {
  const res = await fetch(`https://api.supabase.com/v1${path}`, {
    ...init,
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
  });
  const text = await res.text();
  if (res.status === 401)
    die(
      `Management API rejected the token (401). Re-run \`supabase login\`, or refresh SUPABASE_ACCESS_TOKEN.`,
    );
  if (!res.ok) die(`Management API error ${res.status} on ${path}:\n${text}`);
  try {
    return JSON.parse(text);
  } catch {
    return die(`could not parse Management API response for ${path}:\n${text}`);
  }
}

/** Deployed functions for one project, keyed by slug. */
async function fetchFunctions(ref, token) {
  const list = await api(`/projects/${ref}/functions`, token);
  if (!Array.isArray(list)) die(`unexpected /functions response for ${ref}`);
  return list;
}

/** Vault secret NAMES for one project. `decrypted_secret` is never selected. */
async function fetchSecretNames(ref, token) {
  const rows = await api(`/projects/${ref}/database/query`, token, {
    method: 'POST',
    body: JSON.stringify({ query: 'select name from vault.secrets order by name;' }),
  });
  const list = Array.isArray(rows) ? rows : (rows.result ?? rows.rows ?? []);
  return list.map((r) => r.name).filter(Boolean);
}

async function main() {
  // Found by walking UP so the script works from any cwd, the way the i18n checker's test does.
  let dir = fileURLToPath(new URL('.', import.meta.url).href);
  while (!existsSync(join(dir, 'supabase', 'functions'))) {
    const parent = dirname(dir);
    if (parent === dir) die('could not find supabase/functions above this script');
    dir = parent;
  }
  const repo = readRepoFunctions(join(dir, 'supabase', 'functions'));
  const postures = parseConfigPostures(readFileSync(join(dir, 'supabase', 'config.toml'), 'utf8'));

  const token = accessToken();
  const [stagingFns, productionFns] = await Promise.all([
    fetchFunctions(STAGING_REF, token),
    fetchFunctions(PRODUCTION_REF, token),
  ]);
  const stagingSlugs = stagingFns.map((f) => f.slug).sort();
  const productionSlugs = productionFns.map((f) => f.slug).sort();
  const now = Date.now();

  console.log('\nDeploy parity — repo vs staging vs production   (read-only)\n');
  console.log(`  repo        ${String(repo.length).padStart(3)}   supabase/functions/*/index.ts`);
  console.log(`  staging     ${String(stagingSlugs.length).padStart(3)}   ${STAGING_REF}`);
  console.log(`  production  ${String(productionSlugs.length).padStart(3)}   ${PRODUCTION_REF}\n`);

  const cell = (fns, slug) => {
    const fn = fns.find((f) => f.slug === slug);
    if (!fn) return '— MISSING';
    const status = fn.status && fn.status !== 'ACTIVE' ? ` ${fn.status}` : '';
    return `v${fn.version} ${formatAge(fn.updated_at, now)} ago${status}`;
  };
  const width = Math.max(...repo.map((s) => s.length), 12) + 2;
  console.log(`  ${'function'.padEnd(width)}${'staging'.padEnd(20)}production`);
  for (const slug of repo)
    console.log(
      `  ${slug.padEnd(width)}${cell(stagingFns, slug).padEnd(20)}${cell(productionFns, slug)}`,
    );

  const { missingFromStaging, missingFromProduction, orphanStaging, orphanProduction } =
    diffDeployments({ repo, staging: stagingSlugs, production: productionSlugs });

  for (const [label, slugs] of [
    ['deployed on staging with no repo directory', orphanStaging],
    ['deployed on production with no repo directory', orphanProduction],
  ])
    if (slugs.length) console.log(`\n  ⚠ ${label}: ${slugs.join(', ')}`);

  const drift = postureDrift({ postures, deployed: [...stagingFns, ...productionFns] });
  if (drift.length) {
    console.log('\n  ⚠ deployed verify_jwt disagrees with supabase/config.toml (rule 8):');
    for (const d of drift)
      console.log(`      ${d.slug}  config ${d.declared} → deployed ${d.deployed}`);
  }

  const [stagingSecrets, productionSecrets] = await Promise.all([
    fetchSecretNames(STAGING_REF, token),
    fetchSecretNames(PRODUCTION_REF, token),
  ]);
  const secrets = diffSecrets({ staging: stagingSecrets, production: productionSecrets });
  console.log('\nVault secret names   (names only — no value is ever read)\n');
  console.log(`  staging     ${String(stagingSecrets.length).padStart(3)}`);
  console.log(`  production  ${String(productionSecrets.length).padStart(3)}`);
  console.log(`  staging-only     ${secrets.stagingOnly.join(', ') || 'none'}`);
  console.log(`  production-only  ${secrets.productionOnly.join(', ') || 'none'}`);
  if (secrets.expectedStagingOnly.length)
    console.log(
      `  expected staging-only, NOT drift: ${secrets.expectedStagingOnly.join(', ')} — guards seed-staging.sql; must never exist on production`,
    );
  if (secrets.unexpectedOnProduction.length)
    console.log(
      `\n  ⚠⚠ ON PRODUCTION AND MUST NOT BE: ${secrets.unexpectedOnProduction.join(', ')} — this arms the staging seed against production. Remove it.`,
    );

  // The one gate. Absence only — see the header.
  const failures = [
    ['staging', missingFromStaging],
    ['production', missingFromProduction],
  ].filter(([, slugs]) => slugs.length);
  if (failures.length) {
    console.error('');
    for (const [project, slugs] of failures)
      console.error(`✗ not deployed to ${project}: ${slugs.join(', ')}`);
    console.error('');
    process.exit(1);
  }
  console.log('\n✓ every repo function is deployed to both projects.\n');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await main();
