// Shared flat ESLint config for the pure-TypeScript workspace packages
// (core, api, schemas, i18n, config).
//
// Why this exists: the repo had exactly two ESLint configs — apps/native (eslint-config-expo)
// and apps/web (eslint-config-next) — so `pnpm turbo lint` ran on 2 of 7 workspaces and every
// packages/* file was unlinted. Neither framework preset fits a package with no React, no
// Next runtime and no Metro: expo's brings react-hooks/react-native rules, next's brings
// core-web-vitals. This is the third preset, and it is the pure-TS one.
//
// Distributed the same way the tsconfig presets already are (`@athanor/config/tsconfig/*`),
// so a consumer is a one-line re-export.

import js from '@eslint/js';
import tseslint from 'typescript-eslint';

/**
 * @param {object} [opts]
 * @param {string} opts.tsconfigRootDir - the consuming package's directory (`import.meta.dirname`).
 *   Required: type-aware linting needs to resolve that package's own tsconfig, not this one's.
 * @returns {import('typescript-eslint').ConfigArray}
 */
export function libraryConfig({ tsconfigRootDir }) {
  return tseslint.config(
    {
      // Generated, vendored or build output — none of it is ours to lint.
      // `database.types.ts` is regenerated by `pnpm gen:types` and a PreToolUse hook
      // blocks editing it, so a lint error there would be unfixable by construction.
      ignores: ['coverage/**', 'reports/**', '.stryker-tmp/**', 'dist/**', 'src/database.types.ts'],
    },
    js.configs.recommended,
    ...tseslint.configs.recommendedTypeChecked,
    {
      languageOptions: {
        parserOptions: {
          projectService: true,
          tsconfigRootDir,
        },
      },
      rules: {
        // The tsconfig preset already sets `noUnusedLocals`-adjacent strictness via tsc;
        // ESLint's version adds the `_`-prefix escape hatch that tsc lacks.
        '@typescript-eslint/no-unused-vars': [
          'error',
          { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
        ],
        // Rule #1 territory: these packages are the domain core. An implicit `any` leaking
        // through a boundary is how an unvalidated shape reaches the score engine.
        '@typescript-eslint/no-explicit-any': 'error',
        // `catch (e) { throw e }` and `await`-on-non-promise are the two type-aware checks
        // that have caught real defects in this repo's query layer; keep them at error.
        '@typescript-eslint/require-await': 'error',
        '@typescript-eslint/no-floating-promises': 'error',
      },
    },
    {
      // Test files: the fakes in `src/test-support` and the `*.test.ts` files deliberately
      // build malformed payloads to drive the failure arms, so the type-aware rules that
      // police production boundaries are noise here — but `no-explicit-any` stays on, since
      // a test that types its fixture as `any` stops proving the shape it claims to prove.
      files: ['**/*.test.ts', 'src/test-support/**/*.ts'],
      rules: {
        '@typescript-eslint/no-unsafe-assignment': 'off',
        '@typescript-eslint/no-unsafe-member-access': 'off',
        '@typescript-eslint/no-unsafe-argument': 'off',
        '@typescript-eslint/no-unsafe-call': 'off',
        '@typescript-eslint/no-unsafe-return': 'off',
        // A fake of an async API must be `async` even with nothing to await — the shape it
        // mirrors returns a Promise, and `maybeSingle: () => ({...})` would not be that shape.
        // The rule is asking a question that has no answer here, not catching a defect.
        '@typescript-eslint/require-await': 'off',
      },
    },
    {
      // Tooling files (vitest.config.ts, eslint.config.js, this preset itself) sit outside
      // the `include: ["src"]` of the tsconfig preset, so the project service cannot resolve
      // them and type-aware rules hard-error. Lint them syntactically only.
      files: ['*.config.{ts,js,mjs}', 'eslint/**/*.js'],
      extends: [tseslint.configs.disableTypeChecked],
    },
  );
}
